### ISSUE TITLE
Misc. visual feedback

### ISSUE THREAD

**Issue by nixolas1** [chrisdancee/react-ios-pwa-prompt#31]
Hi, very nice plugin / package. Saved me for a lot of work :)
A few suggestions on ux and ui:
1. Have a bit more contrast on the text, at least the text for the steps. 
2. The Share and Add icons in the steps look very clickable. During a quick user test they tried clicking the icons in the popup instead of the share button below (on mobile). Maybe move them after the text could help? Maybe direct the user to the real share button somehow? Not sure.
3. For debugging and testing it would be useful with a prop that forces it to show, no matter OS or state.

Again, great work, and if you add a donate button somewhere, I'm sure people will use it ;)

Cheers,
Nix

**Comment by nixolas1** [comment]
(it seems the text contrast was just bad on dark mode. I think it uses the normal-mode text color, and not the dark mode one?)

**Comment by chrisdancee** [comment]
Hi @nixolas1, sorry for the delay in getting back to you - I've been away.
Will take a look into this tonight. Thank you for your kind words and for your feedback!

**Comment by chrisdancee** [comment]
Hi @nixolas1, thanks a lot for the feedback. Had a proper chance to assess what you'd written and it's been very useful. I have merged and released some changes in v1.5.0 that should address these issues.

I have added a debug mode, which is a very simple but useful addition. I improved the contrast, and used the actual colours used by apple instead of trying to guess. And the prompt now stops the user from scrolling, which has the side effect of showing the bottom menu bar - I think this improves the UX and makes it clearer to the user where they should be pressing.

I have also updated the default text, this also messed up the numbering slightly as the bottom line is in line with the number (which bugs me to no end), but fixing this will be a breaking change and so I will resolve later.

Thanks again for the feedback and time spent testing, I will be closing this issue - but feel free to open another if you think any of the changes are not effective enough at achieving better UX.
